### ISSUE TITLE
Is there any way to use ComPtr in structs?

### ISSUE THREAD

**Issue by CarePackage17** [retep998/wio-rs#16]
I was trying to port one of Chuck Walbourn's D3D11 C++ templates to Rust, but ran into following problem:
In C++ there's a `Game` class that manages D3D resources via WRL ComPtr<T>. I wanted to do it the same way, but can't construct a null wio::ComPtr without it throwing an assert due to being null. Because of that I can't really create an instance of `Game` in Rust, because for that I'd already need valid D3D device pointers.

Any pointers (badum-tss!) on how I can resolve this? Or should I use [this crate](https://github.com/Eljay/com-rs) instead?

**Comment by retep998** [comment]
`Option<ComPtr<T>>` is the same size as `ComPtr<T>` thanks to `NonNull` optimizations and allows you to handle the null case.

**Comment by CarePackage17** [comment]
Huh, it seems I missed the forest for the trees on this one. Thanks for the help!

**Comment by CarePackage17** [comment]
As a follow up, how would I explicitly drop (Reset() in WRL) a ComPtr without dropping its containing struct? There is no way it can go out of scope.
I can assign None since it's an Option<T>, but will that run ComPtr's destructor?

**Comment by retep998** [comment]
If you have an `Option<T>` and you assign `None` to it, any contained value will be dropped.

**Comment by CarePackage17** [comment]
I wanted to follow up with "what sorcery is this?" and "where is this documented?", then found this in the [reference](https://doc.rust-lang.org/beta/reference/destructors.html):

> Assignment also runs the destructor of its left-hand operand, unless it's an uninitialized variable.

Thanks a lot, you can close this now.
