### ISSUE TITLE
Invalid handle with Wine

### ISSUE THREAD

**Issue by gwenn** [retep998/wio-rs#5]
On an Arch Linux machine:

``` sh
cargo run --example console --target 'x86_64-pc-windows-gnu'
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading winapi v0.2.8
 Downloading user32-sys v0.1.2
 Downloading libc v0.2.14
   Compiling libc v0.2.14
   Compiling winapi v0.2.8
   Compiling rand v0.3.14
   Compiling winapi-build v0.1.1
   Compiling kernel32-sys v0.2.2
   Compiling user32-sys v0.1.2
   Compiling wio v0.1.1 (file:///home/vagrant/wio-rs)
     Running `target/x86_64-pc-windows-gnu/debug/examples/console.exe`
fixme:thread:SetThreadStackGuarantee (0x32fba0): stub
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 6, message: "Invalid handle." } }', ../src/libcore\result.rs:788
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: Process didn't exit successfully: `target/x86_64-pc-windows-gnu/debug/examples/console.exe` (exit code: 101)
```

Maybe it is related to Wine.
But there is no error when running the `linenoise-ng` example which seems to use the same API:

```
mkdir build && cd build
cmake -DCMAKE_TOOLCHAIN_FILE=~/Toolchain-x86_64-pc-windows-gnu.cmake -DCMAKE_BUILD_TYPE=Debug ..
make
./example.exe
starting...
linenoise>
```

Thanks.

**Comment by retep998** [comment]
Could you try to figure out which exact function call is returning that error? The code runs fine for me on Windows, so it's probably something particular that I'm doing which wine doesn't like.

**Comment by gwenn** [comment]
Ok,
https://github.com/retep998/wio-rs/blob/master/examples/console.rs#L9
https://github.com/retep998/wio-rs/blob/master/src/console.rs#L17

**Comment by retep998** [comment]
So it appears that wine is unable to handle creating new console screen buffers? Can you figure out whether there is some invocation of `CreateConsoleScreenBuffer` which does work fine?

**Comment by gwenn** [comment]
It appears that `linenoise-ng` does not use `CreateConsoleScreenBuffer`.
And I can't make `CreateConsoleScreenBuffer` work with Wine.
Sorry for the inconvenience, it is not related to `wio-rs`...

**Comment by retep998** [comment]
According to https://www.winehq.org/docs/wineusr-guide/cui-programs, did you try running it with wineconsole? Perhaps trying different backends?

**Comment by gwenn** [comment]
Many thanks for you help.

I have no X server:

``` sh
$ wineconsole target/x86_64-pc-windows-gnu/debug/examples/console.exe
err:winediag:nulldrv_CreateWindow Application tried to create a window, but no driver could be loaded.
err:winediag:nulldrv_CreateWindow Make sure that your X server is running and that $DISPLAY is set correctly.
```

And

``` sh
$ wineconsole --backend=curses target/x86_64-pc-windows-gnu/debug/examples/console.exe
$ echo $?
101
```

But:

``` sh
$ # just a check with linenoise-ng
$ wineconsole --backend=curses example.exe
$ echo $?
0
```

The `curses` backend seems to work properly (fullscreen display and color with `linenoise-ng`).
And with these lines added in the `linenoise-ng` example:

``` cpp
     HANDLE mScreenBuf = CreateConsoleScreenBuffer (GENERIC_READ | GENERIC_WRITE, FILE_SHARE_WRITE, 0,
                                     CONSOLE_TEXTMODE_BUFFER, 0);
     if (mScreenBuf == INVALID_HANDLE_VALUE) {
         printf("CreateConsoleScreenBuffer failed!\n");
         exit(1);
     } else {
         printf("CreateConsoleScreenBuffer succeeded!\n");
         CloseHandle (mScreenBuf);
     }
```

It works:

``` sh
$ # wineconsole OK
$ wineconsole --backend=curses example.exe
CreateConsoleScreenBuffer succeeded!
starting...
linenoise>
$ # wine KO
$ wine example.exe 
CreateConsoleScreenBuffer failed!
```

**Comment by retep998** [comment]
That crash, does it occur with other rust programs when you use the curses backend? Could you perhaps use a debugger to figure out how it is crashing?
